### ISSUE TITLE
`[FEAT]` - Desenvolver componente de Depoimento de Aluno

### ISSUE THREAD

**Issue by odavibatista** [odavibatista/wits-site-webapp#12]
### Descrição:

![image](https://github.com/user-attachments/assets/ae0f5b68-657d-40b1-b559-8c4b01f35e85)

### RN:

Componente deve receber as seguintes props via interface Typescript:
- photo;
- student_name;
- testimony_text;
- profession.

**Comment by thenrybruno** [comment]
Em desenvolvimento

**Comment by thenrybruno** [comment]
Desenvolvido e mergeado com a branch dev
