### ISSUE TITLE
`[FEAT]` - Desenvolver componente Header

### ISSUE THREAD

**Issue by odavibatista** [odavibatista/wits-site-webapp#15]
#### Não autenticado:
![image](https://github.com/user-attachments/assets/ffc2f1c9-c4a5-4caf-9156-6e49410f5096)

#### Autenticado:
(EM PROGRESSO)

### RN:

Componente possui dois estados.
- O estado não autenticado deve ser exibido caso o usuário não esteja logado no site;
- O estado autenticado deve ser exibido caso o usuário esteja logado no site.

**Comment by thenrybruno** [comment]
Enviei um PR com o HeaderNoAuth feito

**Comment by thenrybruno** [comment]
Finalizado
