### ISSUE TITLE
`[FEAT]` - Desenvolver componente de Botão de Plataforma

### ISSUE THREAD

**Issue by odavibatista** [odavibatista/wits-site-webapp#19]
### Descrição:

![image](https://github.com/user-attachments/assets/5d92f1a1-34e4-41c0-b8fc-2ed1e3c9230e)

### RN:

Componente deve possuir uma interface Typescript contendo as seguintes props:
- platform_name;
- image_url;

**Comment by thenrybruno** [comment]
Componente feito
